import { SoundId, SoundSource } from './types';

/**
 * Typed sound registry. The original Swift project shipped NO audio, so these
 * are original synthesized placeholder WAVs generated by
 * scripts/generate-placeholder-sounds.mjs (sine waves + noise — nothing
 * sampled or copyrighted). Swap any entry for a produced SFX file later; the
 * service no-ops safely if an entry is set back to null.
 */
export const soundRegistry: Readonly<Record<SoundId, SoundSource>> = {
  cardDeal: require('../../../assets/audio/card-deal.wav'),
  cardFlip: require('../../../assets/audio/card-flip.wav'),
  chipTap: require('../../../assets/audio/chip-tap.wav'),
  betPlaced: require('../../../assets/audio/bet-placed.wav'),
  win: require('../../../assets/audio/win.wav'),
  loss: require('../../../assets/audio/loss.wav'),
  push: require('../../../assets/audio/push.wav'),
  levelUp: require('../../../assets/audio/level-up.wav'),
  achievementUnlock: require('../../../assets/audio/achievement-unlock.wav'),
  shuffle: require('../../../assets/audio/shuffle.wav'),
  buttonTap: require('../../../assets/audio/button-tap.wav'),
  meterTopUp1: require('../../../assets/audio/meter-top-up-1.wav'),
  meterTopUp2: require('../../../assets/audio/meter-top-up-2.wav'),
  meterTopUp3: require('../../../assets/audio/meter-top-up-3.wav'),
  meterTopUp4: require('../../../assets/audio/meter-top-up-4.wav'),
  meterTopUp5: require('../../../assets/audio/meter-top-up-5.wav'),
  meterTopUp6: require('../../../assets/audio/meter-top-up-6.wav'),
  meterTopUp7: require('../../../assets/audio/meter-top-up-7.wav'),
  meterTopUp8: require('../../../assets/audio/meter-top-up-8.wav'),
};
